using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ethier.Model
{

    public class ApexScaleTicket
    {
        public string TicketType { get; set; }
        public int TicketNo { get; set; }
        [Key]
        public int UniqueID { get; set; }
        public short ItemNo { get; set; }
        public DateTime TicketDate { get; set; }
        public DateTime TicketTime { get; set; }
        public long DispatchNo { get; set; }
        public int DispatchLoadID { get; set; }
        public DateTime DispatchDate { get; set; }
        public string LocationID { get; set; }
        public string CustomerID { get; set; }
        public string OrderID { get; set; }
        public string OrderItem { get; set; }
        public string ProductID { get; set; }
        public string MixID { get; set; }
        public string FeeCodeID { get; set; }
        public string TaxCodeID { get; set; }
        public string JobID { get; set; }
        public string JobCostID { get; set; }
        public string PurchaseOrder { get; set; }
        public string ReleaseID { get; set; }
        public string CustomerJob { get; set; }
        public string CarrierID { get; set; }
        public string VehicleID { get; set; }
        public string DriverID { get; set; }
        public string Trailer1 { get; set; }
        public string Trailer2 { get; set; }
        public string Trailer3 { get; set; }
        public string MasterOrderID { get; set; }
        public string ZoneID { get; set; }
        public string CityID { get; set; }
        public string LoadStationID { get; set; }
        public string BinID { get; set; }
        public string Description { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string DeliveryAddress3 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public short ScaleIDGross { get; set; }
        public short ScaleIDTare { get; set; }
        public string ScaleUnitID { get; set; }
        public int Gross { get; set; }
        public int Tare { get; set; }
        public int Net { get; set; }
        public double Qty { get; set; }
        public string Unit { get; set; }
        public double FreightQty { get; set; }
        public string MatlUnitID { get; set; }
        public string FreightUnitID { get; set; }
        public string VoidStatus { get; set; }
        public string VoidReason { get; set; }
        public string ShipOrReceive { get; set; }
        public string SellOrBuy { get; set; }
        public string CashStatus { get; set; }
        public string PostStatus { get; set; }
        public string OkStatus { get; set; }
        public string ExportStatus { get; set; }
        public string VehicleType { get; set; }
        public string TrailerType1 { get; set; }
        public string TrailerType2 { get; set; }
        public string TrailerType3 { get; set; }
        public string FreightFob { get; set; }
        public string FreightStatus { get; set; }
        public string FreightMode { get; set; }
        public string FreightType { get; set; }
        public string FreightRateType { get; set; }
        public string GrossStatus { get; set; }
        public string TareStatus { get; set; }
        public string NetStatus { get; set; }
        public int MsgID { get; set; }
        public string TicketMessage { get; set; }
        public string TicketMessage2 { get; set; }
        public short TodayLoads { get; set; }
        public double TodayQty { get; set; }
        public int OrderLoads { get; set; }
        public double OrderQty { get; set; }
        public int LotNo { get; set; }
        public int LotLoadNo { get; set; }
        public double LotAccumQty { get; set; }
        public int Train { get; set; }
        public DateTime LoadDate { get; set; }
        public DateTime LoadTime { get; set; }
        public DateTime DateIn { get; set; }
        public DateTime TimeIn { get; set; }
        public DateTime CheckInDate { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime UserDate { get; set; }
        public DateTime UserTime { get; set; }
        public string ShipVia { get; set; }
        public string ShipTerms { get; set; }
        public string PayMethod { get; set; }
        public int PayRefID { get; set; }
        public string PayInfo { get; set; }
        public string ReturnTicket { get; set; }
        public string PrevailingWage { get; set; }
        public int ReferTicketNo { get; set; }
        public int ReferUniqueID { get; set; }
        public string LoginLocationID { get; set; }
        public string TransLocationID { get; set; }
        public string SourceID { get; set; }
        public string DestinationID { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovalCode { get; set; }
        public string ApprovalUserID { get; set; }
        public DateTime ApprovalDateTime { get; set; }
        public int ItemCount { get; set; }
        public string MapBook { get; set; }
        public string Page { get; set; }
        public string Grid { get; set; }
        public string Block { get; set; }
        public string Lot { get; set; }
        public string ScaleStatType { get; set; }
        public string ScaleStatLocationID { get; set; }
        public int ScaleStatScaleID { get; set; }
        public int ScaleStatMsgID { get; set; }
        public string ShipTo { get; set; }
        public string ShipLocationID { get; set; }
        public string UseDeliveredPrice { get; set; }
        public string MaxWeightLimit { get; set; }
        public string SpecialPricing { get; set; }
        public string Repriced { get; set; }
        public string SplitMaterialFreight { get; set; }
        public int ExternalMsgID { get; set; }
        public string SubstituteProductID { get; set; }
        public string ReceiveStatus { get; set; }
        public string PodTicketReceived { get; set; }
        public DateTime PodDate { get; set; }
        public DateTime PodTime { get; set; }
        public string OriginSystem { get; set; }
        public double AcQty { get; set; }
        public double Slump { get; set; }
        public double SlumpAtDestination { get; set; }
        public double Calcium { get; set; }
        public short AirEntrainment { get; set; }
        public short SuperPlasticizer { get; set; }
        public short HotWater { get; set; }
        public short Ice { get; set; }
        public short Water { get; set; }
        public short WaterMax { get; set; }
        public short DistanceToDest { get; set; }
        public string ApplyMinimums { get; set; }
        public string CMRNumber { get; set; }
        public double VendorQty { get; set; }
        public int LoadTargetGross { get; set; }
        public int LoadTargetNet { get; set; }
        public int VarianceTargetNet { get; set; }
        public string UfText1 { get; set; }
        public string UfCustomerOrder1 { get; set; }
        public string UfCustomerOrder2 { get; set; }
        public string UfCustomerOrder3 { get; set; }
        public string UfCustomerOrder4 { get; set; }
        public string UfCustomerOrder5 { get; set; }
        public string UfCustomerOrder6 { get; set; }
        public string UfOrderDispatch1 { get; set; }
        public string UfOrderDispatch2 { get; set; }
        public string UfLocationProduct1 { get; set; }
        public string UfType1 { get; set; }
        public string UfType2 { get; set; }
        public string UfType3 { get; set; }
        public string UfType4 { get; set; }
        public string UfType5 { get; set; }
        public string UserID { get; set; }
        public string InvoiceStatus { get; set; }
        public int InvoiceNo { get; set; }
        public int InvoiceUniqueID { get; set; }
        public string MiscStatus { get; set; }
        public int PreviousUniqueID { get; set; }
        public int NextUniqueID { get; set; }
        public string Closed { get; set; }
        public string Reconciled { get; set; }
        public string Credited { get; set; }
        public int BatchID { get; set; }
        public int BatchIDAp { get; set; }
        public int BatchIDAr { get; set; }
        public double MinimumQty { get; set; }
        public double MinimumFreightQty { get; set; }
        public double MinimumFreightPayQty { get; set; }
        public string Incoterms { get; set; }
        public string PriceSource { get; set; }
        public string FreightRateSource { get; set; }
        public string FreightPaySource { get; set; }
        public int ShipmentNo { get; set; }
        public int ShipmentUniqueID { get; set; }
        public string VehicleWeightCalc { get; set; }
        public string SplitLoad { get; set; }
        public short SplitLoadCount { get; set; }
        public int SplitLoadTotalGross { get; set; }
        public int SplitLoadTotalTare { get; set; }
        public int SplitLoadTotalNet { get; set; }
        public string SplitCaptureMethod { get; set; }
        public int SplitCapture1 { get; set; }
        public int SplitCapture2 { get; set; }
        public int SplitCapture3 { get; set; }
        public int SplitCapture4 { get; set; }
        public string SplitCap1CertGUID { get; set; }
        public string SplitCap2CertGUID { get; set; }
        public string SplitCap3CertGUID { get; set; }
        public string SplitCap4CertGUID { get; set; }
        public int TrailerTare1 { get; set; }
        public int TrailerTare2 { get; set; }
        public int TrailerTare3 { get; set; }
        public string TrailrTare1CertGUID { get; set; }
        public string TrailrTare2CertGUID { get; set; }
        public string TrailrTare3CertGUID { get; set; }
        public string IsMultiTktSplitLoad { get; set; }
        public int ReferSplitTicketNo { get; set; }
        public int ReferSplitUniqueID { get; set; }
        public string PackageManuallySet { get; set; }
        public double BasePackageAmount { get; set; }
        public double EndingPackageAmount { get; set; }
        public double AltTicketQty { get; set; }
        public string AltTicketUnitID { get; set; }
        public short AltTicketQtyEdited { get; set; }
        public int CvtNetWeight { get; set; }
        public string CvtNetUnitID { get; set; }
        public string MatlUseCvtNet { get; set; }
        public string FreightUseCvtNet { get; set; }
        public string FreightPayUseCvtNet { get; set; }
        public string AltTicketUseCvtNet { get; set; }
        public string FactorGroupID { get; set; }
        public string MobileTktSubmitted { get; set; }
        public string ToleranceOverridden { get; set; }
        public string JourneyUID { get; set; }
        public int JourneyItemNo { get; set; }
        public int TicketPrinterID { get; set; }
        public int ReprintCount { get; set; }
        public string GrossCertGUID { get; set; }
        public string TareCertGUID { get; set; }
        public string GlobalUID { get; set; }
        public int NotesID { get; set; }
        public DateTime AuditDate { get; set; }
        public DateTime AuditTime { get; set; }
        public string AuditUserID { get; set; }
        public string AuditType { get; set; }
        public int AuditUID1 { get; set; }
        public int AuditUID2 { get; set; }
        public string AuditTransferred { get; set; }
        public int XfrGroupNo { get; set; }
        public int XfrSequenceNo { get; set; }
        public short XfrGroupCount { get; set; }
        public string OrgCompanyID { get; set; }
    }
   
}
